version: '3.8'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: users
      MYSQL_DATABASE: users_db
      MYSQL_USER: usersmsvc
      MYSQL_PASSWORD: usersmsvc

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
